quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url= jdbc:postgresql://localhost:5432/todo
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

#quarkus.flyway.migrate-at-start=true

todo-api/mp-rest/url=https://jsonplaceholder.typicode.com/users

consul.host=127.0.0.1
consul.port=8500

# Plantilla Stork (Solo usar cuando conecto MIS microservicios entre sí)

# 1. Le decimos al cliente que no use HTTP normal, sino que use la magia de Stork
mi-cliente-api/mp-rest/url=stork://nombre-del-otro-microservicio

# 2. Le decimos a Stork cómo ir a preguntarle a Consul
quarkus.stork.nombre-del-otro-microservicio.service-discovery.type=consul
quarkus.stork.nombre-del-otro-microservicio.service-discovery.consul-host=${consul.host}
quarkus.stork.nombre-del-otro-microservicio.service-discovery.consul-port=${consul.port}
quarkus.stork.nombre-del-otro-microservicio.service-discovery.application=nombre-exacto-del-otro-microservicio
quarkus.stork.nombre-del-otro-microservicio.service-discovery.refresh-period=5s

quarkus.container-image.group=jsquinatoa
quarkus.container-image.name=app-todo
quarkus.container-image.build=true
quarkus.container-image.push=true